pkg/protocol/header.go
refactor
en: use errors.NewPublic in hertz rather than fmt.Errorf when string formatting is not required.
zh: 当字符串不需要格式化时，使用 hertz 的 errors.NewPublic 创建 error 而不是使用 fmt.Errorf。
None
=> refactor: use errors.NewPublic rather than fmt.Errorf

pkg/app/context_test.go, pkg/app/fs.go, pkg/app/fs_test.go
https://github.com/cloudwego/hertz/issues/32
remove fshandler and related tests
=> fix: remove fshandler and related tests

pkg/common/utils/path.go
refactor
en:
1. When the length of substr is 1, we can call strings.IndexByte directly rather than calling len() for substr and then calling strings.IndexByte in strings.Index.
2. We can assign variable as string type instead of int type so that we are able to leave out the work about converting integer to string.
3. net.JoinHostPort() will judge whether `:` is in addr again, and will concat host and port if `:` is not in addr. However, when we call net.JoinHostPort in AddingMissingPort, `:` should not in addr. So we can also concat host and port directly instead of calling net.JoinHostPort.
zh:
1. 当子串长度确定为1时，可以直接调用 strings.IndexByte 函数而不是像 strings.Index 一样先调用 len() 判断子串长度后再调用 strings.IndexByte 函数.
2. 为省去整型数字转字符串的工作，可以将相关变量直接定义成string类型而不是int类型。
3. net包下的 JoinHostPort 函数会再次判断 `:` 是否在 addr …
=> refactor: simplify code in AddMissingPort

pkg/app/middlewares/server/recovery/recovery.go
optimize
en: use `CtxErrorf` instead of `Errorf` when server panic
zh: 使用 `CtxErrorf` 代替 `Errorf` 当服务panic
=> optimize(recovery):use CtxErrorf instead of Errorf when server panic

pkg/app/context.go, pkg/app/server/binding/request.go
refactor
[S1031](https://staticcheck.io/docs/checks/#S1031) - Omit redundant nil check around loop
=> refactor: omit redundant nil check around loop

pkg/protocol/request.go
refactor: unify the entry of setting request options
en: unify the entry of setting request options to prevent options uninitialized from causing panic
zh: 统一设置 request options 的入口，防止 options 未初始化导致 panic
=> refactor: unify the entry to set request options

pkg/protocol/header.go
feat: header add VisitAllCustomHeader method
en: Add the VisitAllCustomHeader method to the request header, so that the incoming function f only works on custom headers( all headers except cookie, host, content-length, content-type, user-agent and connection)
zh: 在 request header 上添加 VisitAllCustomHeader 方法，使得传入的函数 f 只作用在用户自定义的 header 上（除了 cookie, host, content-length, content-type, user-agent 和 connection 以外的 header）。
=> feat: header add VisitAllCustomHeader method

pkg/app/context.go
feat: add ctx.Body()
en: add ctx.Body() method
zh: 添加 ctx.Body() 方法
=> feat: add ctx.Body()

pkg/common/errors/errors.go, pkg/protocol/http1/server.go, pkg/route/engine.go, pkg/route/engine_test.go
Change-Id: I22d17642339ece5f198936bf30bd50768808f46a
feat
EN: close connection after responding the short-connection request
ZH: 短连接响应写回后主动关闭连接
Fixes #30
=> feat: close connection after responding the short-connection request

pkg/common/adaptor/request.go, pkg/common/adaptor/request_test.go, pkg/common/adaptor/response.go
feat: add net/http adaptor
en: Add adaptor for Hertz Request & Response to net/http Request & ResponseWriter
zh: 增加 Hertz Request & Response 到 net/http Request & ResponseWriter 的适配器
=> feat: add net/http adaptor

.github/workflows/pr-check.yml, .github/workflows/tests.yml
fix
en: ci may be dispatched to the arm machine, resulting in an error exec format error
zh: ci 可能被调度到 arm 机器上导致报错 exec format error
=> fix: ci exec /bin/license-eye: exec format error

pkg/app/fs.go
fix
en: cacheLock may fail to be unlocked for potenial panic.
zh: cacheLock 可能会因潜在发生的panic导致解锁失败。
=> fix: use defer to guarantee that mutex will be unlocked

pkg/protocol/consts/default.go, pkg/protocol/http1/client.go
feat(client)
en: Hertz client turns off the default retry logic
zh: Hertz client 关闭默认的重试逻辑
=> feat: client removes default retry logic

pkg/route/routergroup.go
optimize
en: avoid parsing regular expression repeatly by calling regexp.MustCompile in advance.
zh: 通过提前调用regexp.MustCompile，避免程序重复解析正则表达式。
=> optimize: avoid parsing regular expression repeatly

pkg/protocol/http1/req/request_test.go, pkg/protocol/request.go
feat
en: fix an issue that stream data in request body cannot be read when encoded by x-www-form-urlencoded
zh: 修正了 x-www-form-urlencoded 编码下无法读到 bodystream 类型数据
=> feat: parse post args in bodystream

pkg/network/standard/connection.go
feat
en: Connection.Release() is called in the `Read` method of the standard network library to prevent OOM caused by not recycle memory when the `Read` method is called several times in small quantities.
zh: 标准网络库 Read 方法中调用 connecton.Release()，防止在多次少量调用 Read 方法时不回收内存导致的 OOM。
=> feat: release buffer in standard network `Read` method

pkg/app/fs.go, pkg/protocol/header.go, pkg/protocol/header_timing_test.go
optimize
en: Pre-allocate slice when calling bytesconv.AppendHTTPDate, which prevents extra copying.
zh: 调用bytesconv.AppendHTTPDate时，为切片预分配容量，以防止产生额外的拷贝。
=> optimize: pre-allocate slice when calling bytesconv.AppendHTTPDate

pkg/protocol/request.go
fix 
EN: fix the bug that `isTLS` field is not reset when recycle Request
ZH: 修复了 `isTLS` 字段在 Request 回收阶段未正确重置的问题
fixes #163
=> fix: missing reset isTLS field when recycle Request

pkg/route/routes_test.go
test: correcting TestRouterMiddlewareAndStatic
correcting test case
Fixes #173
=> test: correcting TestRouterMiddlewareAndStatic

pkg/app/client/client.go, pkg/app/client/client_test.go, pkg/app/client/option.go, pkg/common/config/client_option.go, pkg/network/dialer/dialer.go, pkg/protocol/client/client.go, pkg/protocol/consts/default.go, pkg/protocol/http1/client.go, pkg/protocol/http1/client_test.go, pkg/protocol/http1/proxy/proxy.go
refactor
EN: distinguish between global dialer and local dialer & remove dialFunc(use dialer as an alternative)
ZH：区别全局默认dialer和client 局部dialer（指定了dialer的client不再受全局dialer改变而改变）修改全局dialer影响面较大，标记deprecated，后续统一到client初始化时传参指定dialer方式修改局部dialer，以及移除了功能完全被dialer覆盖的dialFunc扩展
=> refactor: distinguish between global dialer and local dialer

pkg/common/utils/path.go, pkg/common/utils/path_test.go
fix
EN: add support for bare v6 address in AddMissingPort function
ZH：AddMissingPort函数增加对裸v6地址的处理
=> add v6 support for AddMissingPort function

pkg/common/utils/network.go
fix
- zh: 获取到了错误的ipv6本地回环地址
- en: get wrong local loopback IPV6
本地环境获取localip时获取到 `fe80::1%lo0`，不符合预期。
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
inet 127.0.0.1 netmask 0xff000000
inet6 ::1 prefixlen 128
inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
nd6 options=201<PERFORMNUD,DAD>
```
=> fix: get wrong local loopback IPv6

pkg/app/server/hertz.go, pkg/route/engine.go
fix
- zh: 修复取消注册失败当服务停止时
- en: fix deregister failed  when service shutdown
=> fix: deregister failed  when service shutdown

pkg/app/context.go, pkg/app/context_test.go
optimize
- 添加 RequestContext.SetCookie 方法
en: add RequestContext.SetCookie Method
zh(optional): 添加 RequestContext.SetCookie 方法
currently hertz is used to set cookies:
```go
h.GET("/cookie", func(ctx context.Context, c *app.RequestContext) {
// set a cookie
cookie := protocol.AcquireCookie()
cookie.SetKey("myCookie")
cookie.SetValue("a nice cookie!")
cookie.SetExpire(time.Now().Add(3600 * time.Second))
cookie.SetPath("/")
cookie.SetHTTPOnly(true)
cookie.SetSecure(false)
c.Response.Header.SetCookie(cookie)
protocol.ReleaseCookie(cookie)
c.WriteString("A cookie is ready.")
return
}
```
after:
```go
h.GET("/cookie", func(ctx context.Context, c *app.RequestContext) {
// set a cookie
c.SetCookie("user", "hertz", 1, "/", "localhost", true, true)
c.WriteString("A cookie is ready.")
return
}
```
=> optimize: add RequestContext.SetCookie Method

internal/bytestr/bytes.go, pkg/protocol/uri.go, pkg/protocol/uri_test.go
fix: A bug fix 
修复目录穿越漏洞
en: fix by simply replace all backslashes with forward slashes
zh(optional): 将反斜杠全部改成正斜杠
Fixes https://github.com/cloudwego/hertz/issues/228
Currently hertz has no restriction on backslash in `normalizePath` function.
```go
func normalizePath(dst, src []byte) []byte {
dst = dst[:0]
dst = addLeadingSlash(dst, src)
dst = decodeArgAppendNoPlus(dst, src)
// remove duplicate slashes
b := dst
bSize := len(b)
for {
n := bytes.Index(b, bytestr.StrSlashSlash)
if n < 0 {
break
}
b = b[n:]
copy(b, b[1:])
b = b[:len(b)-1]
bSize--
}
dst = dst[:bSize]
// remove /./ parts
b = dst
for {
n := bytes.Index(b, bytestr.StrSlashDotSlash)
if n < 0 {
break
}
nn := n + len(bytestr.StrSlashDotSlash) - 1
copy(b[n:], b[nn:])
b = b[:len(b)-nn+n]
}
// remove /foo/../ parts
for {
n := …
```
=> fix: fix path-traversal bug

pkg/app/client/client_test.go, pkg/protocol/client/client.go, pkg/protocol/http1/client.go, pkg/protocol/http1/client_test.go
fix
修复 hostclient race 可能导致的串连接问题
en: Fix the wrong connection problem that may be caused by hostclient race
zh: 修复 hostclient race 可能导致的串连接问题
=> fix: client test race

pkg/route/tree.go, pkg/route/tree_test.go
fix: A bug fix
修复一些tsr参数返回错误的bug
en: 1.Registering the route "/a/:b/*c", then request the path "/a/b", the find function in tree.go will return a false tsr so that server return 404 page not found.
2.Registering the route "/aa" and "/a/*b", then request the path "/a", the find function will return a false tsr
3.There's something wrong with the if conditional logic
zh(optional):1.注册"/a/:b/*c"路由，然后发起请求访问/a/b，文件tree.go中find函数会返回一个false的tsr导致无法自动重定向，因此服务端返回了404
2.同时注册"/aa"和"/a/*b", 然后发起请求访问/a，find函数返回false的tsr
3.在上图的if判断语句中存在一些逻辑错误，因为代码走到这的时候search和cn.prefix的前缀并不一定相等
Fixes [#231](https://github.com/cloudwego/hertz/issues/231)
=> fix: fix some tsr bugs

pkg/route/engine.go
feat
添加一个启动日志，显示加载的网络库的名称
en: The log is added to the server startup location
zh: 作为启动日志的一部分，选择在server启动的位置打印网络库名称
Fixes #61
=> feat: add a startup log to display the name of the loaded network library

pkg/app/server/hertz_test.go, pkg/route/engine.go
- fix
- en: add channel signal judge to allow onShutdownHook to complete or timeout
- zh(optional):  添加`channel`信号判断，允许 `onShutdownHook` 执行完成或超时
=> fix: add channel signal judge to allow onShutdownHook to complete or timeout

cmd/hz/internal/config/cmd.go
optimize
将插件软链接到 $GOPATH/bin 下
en: softlink the plugin to $GOPATH/bin
zh(optional): 将插件软链接到 $GOPATH/bin 下
=> optimize: softlink the plugin to $GOPATH/bin

pkg/common/errors/errors.go, pkg/common/errors/errors_test.go
feat
支持`error`的格式化
en: Add three methods: `errors.Newf`, `errors.NewPublicf`, `errors.NewPrivatef` whit unit tests.
zh: 添加了三个方法：`errors.Newf`，`errors.NewPublicf`，`errors.NewPrivatef`，并补充了单元测试。
Fixes #248
=> feat: errors support format

pkg/common/adaptor/request_test.go
test
en: add ut for `hertz/pkg/common/adaptor`, coverage increased from 76.6% to 92.3%
zh(optional): 增加对`hertz/pkg/common/adaptor`的单测，覆盖率从76.6%提高到了92.3%
#257
=> test: add ut for hertz/pkg/common/adaptor

pkg/common/config/client_option_test.go, pkg/common/config/option_test.go, pkg/common/config/request_option_test.go
test: pkg/common/config  test coverage increased from 48.4% to 100%
en: pkg/common/config test coverage
zh(optional): 增加pkg/common/config包测试覆盖率
part of #257
=> test(pkg/common/config):  pkg/common/config test coverage

pkg/app/server/option.go, pkg/app/server/option_test.go, pkg/common/config/option.go, pkg/route/engine.go
optimize
添加一个选项来控制是否执行 `debugPrintRoute`
en: Added an option to control whether to print the route's log when it starts running, the default is to print. If **panic** occurs when there are many routes, because there is a lot of routing startup information, **panic** cannot be seen intuitively. Adding this option can avoid such a situation.
zh(optional): 新增了一个可选项来控制是否在开始运行时打印路由的日志，默认为打印。在路由较多时若发生**panic**，由于有大量的路由启动信息，因此不能直观的看到**panic**，增加此可选项后可避免此类情况出现。
Fixes #268
=> optimize: add a option to controls whether debugPrintRoute executes

pkg/network/standard/connection.go
feat
在标准库上添加 CloseNoResetBuffer 方法
en: add closeNoResetBuffer method for standard network
zh: 在标准库上添加 CloseNoResetBuffer 方法\
=> feat: add closeNoResetBuffer method for standard network

pkg/network/dialer/dialer_test.go, pkg/network/netpoll/connection_test.go, pkg/network/standard/connection_test.go
test
为`pkg/network`补充单元测试
en: 
unit tests coverage improvement：
`pkg/network/dialer`：0% -> 100%
`pkg/network/netpoll`：0% -> 33.8%
`pkg/network/standard`：46.2% -> 75.2%
ps. Unit tests for `pkg/network/standard/dialer.go`,  `pkg/network/standard/transport.go`, `pkg/network/netpoll/dialer.go`, `pkg/network/netpoll/transport.go` are not supplemented due to circular references. Comments with solutions welcome.
zh: 
单测覆盖率提升：
`pkg/network/dialer`：0% -> 100%
`pkg/network/netpoll`：0% -> 33.8%
`pkg/network/standard`：46.2% -> 75.2%
ps. 由于循环引用导致 `pkg/network/standard/dialer.go`,  `pkg/network/standard/transport.go`, `pkg/network/netpoll/dialer.go`, `pkg/network/netpoll/transport.go` 的单测未能补充，如有建议欢迎评论。
具体细节：由于上述文件分别位于`network/standard`和`network/netpoll`包当中，在模拟构造网络请求的时候，使用到了`route`包的Engine，而`route`包impor …
=> test: ut supplementary for pkg/network

pkg/app/client/retry/retry.go
fix
修复retry潜在的bug
en:
1. In the case of the direct initialization definition &http1. HostClient {} in the picture, when the number of retries is greater than 1, the delay time will be calculated, but the retryConfig. DelayPolicy of retryConfig is nil, and when the retryConfig. DelayPolicy function is executed, a nil pointer error will be reported
2. When the MaxJitter of retryConfig is 0, a panic will occur when using retry.RandomDelayPolicy to generate random numbers
3. The negative number moves to the left will become very large, which is unreasonable
zh(optional):
1.图片中直接初始化定义&http1.HostClient{}的情况，retry次数大于1时，就会计算延迟时间，但retryConfig的retryConfig.DelayPolicy为nil，这时候执行retryConfig.DelayPolicy函数就会报空指针错误
2.在retryConfig的MaxJitter为0时，使用retry.RandomDelayPolicy生成随机数时会panic
3.负数左移会变的特别大，不合理
=> fix: potential edge bugs of retry

pkg/protocol/request_test.go
test
为补充 `pkg/protocol/request.go` 单测
en: ut coverage 51.31% -> 85.3%
zh: 单测覆盖率 51.31% -> 85.3%
Part of #257
=> test: enrich unit tests for pkg/protocol/request.go

internal/stats/tracer.go, pkg/app/client/loadbalance/lbcache.go, pkg/app/client/loadbalance/weight_random.go, pkg/app/fs.go, pkg/app/middlewares/server/recovery/recovery.go, pkg/app/server/hertz.go, pkg/app/server/render/html.go, pkg/common/hlog/default.go, pkg/common/hlog/hlog.go, pkg/common/hlog/system.go, pkg/network/netpoll/connection.go, pkg/network/netpoll/transport.go, pkg/network/standard/transport.go, pkg/protocol/cookie.go, pkg/protocol/header.go, pkg/protocol/header_test.go, pkg/protocol/http1/client.go, pkg/protocol/suite/server.go, pkg/route/engine.go
optimize
区分系统日志和默认日志并添加SetCallDepth接口
en: distinguish systemlogger and defaultlogger
zh: 区分系统日志和默认日志
=> optimize(hlog): distinguish systemlogger and defaultlogger

pkg/app/server/binding/binding.go, pkg/app/server/render/json.go, pkg/common/bytebufferpool/bytebuffer.go, pkg/common/json/sonic.go, pkg/common/json/std.go, pkg/protocol/http1/req/request_test.go, pkg/protocol/http1/resp/response_test.go
feat
增加编译tag控制实际使用的json库
en: Add compile tag for json implementation. Sonic is still used by default, but with a cpu compile check. And its available for users to change the default json lib(sonic) to standard json lib through compile tag: `stdjson`
zh(optional): 增加编译tag控制json库的选择。Sonic仍然作为默认实现，不过增加了cpu检测（针对不符合sonic要求的cpu自动切换至标准json库）。同时新增了一个编译tag：`stdjson` 用于主动切换到标准json实现
A better solution to #277
=> feat: add compile tag for json implementation

pkg/app/middlewares/server/recovery/option.go, pkg/app/middlewares/server/recovery/option_test.go, pkg/app/middlewares/server/recovery/recovery.go, pkg/app/middlewares/server/recovery/recovery_test.go
feat
为 recovery 中间件支持用户自定义错误输出格式
=> feat: support errors format for the recovery middleware

pkg/common/json/sonic.go, pkg/common/json/std.go, pkg/network/netpoll/dial.go, pkg/route/default.go
style
去掉 license 顶层的空注释
en: remove empty comments for license
zh(optional): 去掉 license 顶层的空注释
=> style: remove empty comments for license

pkg/app/client/client.go
=> refactor: add SetRetryIf to remain compatible

pkg/app/middlewares/server/recovery/option.go, pkg/app/middlewares/server/recovery/option_test.go, pkg/app/middlewares/server/recovery/recovery.go
=> optimize: modify the default log of the recovery middleware

pkg/network/netpoll/connection.go
optimize
忽略客户端主动断连的写错误
en: change logs level from error to debug if those are the connection error caused by client
zh(optional): 将client导致的连接错误日志级别从error调整为debug，进一步减少对用户的打扰信息
None
=> optimize: ignore flushing error when connection is closed or reset

cmd/hz/internal/protobuf/resolver.go
fix
修复使用 protobuf 生成代码(主idl和依赖idl的package相同)，handler 中缺少 import 的问题
en: Fix the problem of missing import in the handler when using protobuf to generate code (the package of main idl and dependent idl is the same)
zh(optional): 修复使用 protobuf 生成代码(主idl和依赖idl的package相同)，handler 中缺少 import 的问题
=> fix(hz): no import in handler for pb

cmd/hz/go.mod, cmd/hz/go.sum, cmd/hz/internal/app/app.go, cmd/hz/internal/config/argument.go, cmd/hz/internal/config/cmd.go
feat
添加接入thriftgo/protoc第三方插件的接口
en: add plugin flag
zh(optional): 添加接入thriftgo/protoc第三方插件的接口
=> feat(hz): add plugin flag

pkg/app/server/option.go, pkg/common/config/option.go, pkg/route/engine.go, pkg/route/engine_test.go
feat
server 区分局部和全局 transporter
en: change transporter of the hertz instance with option will not effect global transporter, vice versa. Avoid potential problems affecting other instances by modifying the transporter.
zh(optional): 修改 hertz 实例的 transporter 不会影响全局默认的 transporter，反之亦然；避免潜在的因为修改 transporter 导致影响到其他实例的问题。
None
=> feat: distinguish between global and local transporter

pkg/common/hlog/system.go, pkg/common/hlog/system_test.go, pkg/protocol/http1/client.go, pkg/route/engine.go
=> fix: add prefix to no-format log print function when use system logger

cmd/hz/go.sum, cmd/hz/internal/generator/handler.go, cmd/hz/internal/generator/router.go, cmd/hz/internal/util/ast.go, cmd/hz/internal/util/ast_test.go
fix
修复插入import时由于不同系统换行符带来的影响
en: fix the error of inserting to import for different os
zh(optional): 修复插入import时由于不同系统换行符带来的影响
=> fix(hz): fix the error of inserting to import for different os

pkg/app/server/option_test.go
补充 server/option.go 中 `WithWriteTimeout` 的单元测试
en: enrich ut for WithWriteTimeout in server/option.go
zh(optional): 补充 server/option.go 中 `WithWriteTimeout` 的单元测试
null
=> test: enrich ut for WithWriteTimeout in server/option.go

cmd/hz/internal/protobuf/tags.go
json name should be snake like form and query
**What type of PR is this?**
fix
**Check the PR title.**
(Optional) Translate the PR title into Chinese.
修复 json 默认不是下划线的问题
**(Optional) More detail description for this PR(en: English/zh: Chinese).**
**Which issue(s) this PR fixes:**
=> fix(hz): Default json tag alignment protoc-gen-go

pkg/common/test/mock/network.go, pkg/protocol/http1/server.go, pkg/route/engine.go, pkg/route/engine_test.go
optimize
设置 idle timeout 为 0 在不同的网络库下行为一致
en: before this, standard network cannot process requests properly when idle timeout is set to zero, this may be confusing to users. 
zh(optional): 在此之前，标准网络在空闲超时设置为零时无法正确处理请求，这可能会让用户感到困惑。
None
=> optimize: zero idle timeout acts the same

pkg/app/context.go, pkg/app/context_test.go
feat: A new feature
补充常用的Get***函数
en: Supplement usual Get function
zh(optional): 补充常用的Get***函数
Fixes #368
=> feat: add more metadata related APIs to RequestContext

pkg/route/engine.go
Strongly associated with https://github.com/hertz-contrib/http2/pull/1, do it together for the maximum compatibility.
=> Revert "feat: Adapt the logic after moving the http2 logic to hertz-contrib"

pkg/protocol/header.go, pkg/protocol/header_test.go
feat
en: When sending a HTTP request, hertz will always send a Content-Type header, if the value was not specified by the user, it will default to application/x-www-form-urlencoded. This could cause undesirable effects on the server-side. This PR adds the SetNoDefaultContentType method to RequestHeader which when set to true, will omit the Content-Type header entirely if no Content-Type was specified.
zh(optional):
close #360 
https://github.com/cloudwego/hertz/issues/359
=> feat: add RequestHeader.SetNoDefaultContentType

pkg/app/server/hertz_test.go, pkg/protocol/http1/server.go
fix
trace 错误的修改了根 context
en: standard context use the same one in http1.Serve. In the case of long connections, the context will become larger and larger, and in extreme scenarios, the search overhead will be high.
zh: http1 Serve 方法中使用同一个 context。在长连接情况下，会导致 context 越来越大，在极端场景下导致查找开销大。
=> fix: trace changed the root context by mistake

pkg/app/server/hertz_test.go
test
单测启动 server 只需要监听 localhost 地址，无需监听所有地址
en: listen all addr needs more permission in some platform, but it is unnecessary.
zh(optional): 监听所有地址在某些平台上需要更多权限，但这个并没有必要。
=> test: listen localhost instead of all ip addr

pkg/app/middlewares/server/basic_auth/basic_auth_test.go
为pkg/app/middlewares/server/basic_auth添加更多单元测试
en: Add BasicAuth related tests in pkg/app/middlewares/server/basic_auth, basic_auth.go reaches 100% coverage
zh(optional): 添加pkg/app/middlewares/server/basic_auth中BasicAuth相关的测试，basic_auth.go达到100%覆盖
#257
=> test: add more tests for pkg/app/middlewares/server/basic_auth

pkg/route/engine.go
feat
适配将 http2 逻辑挪到 hertz-contrib 后的逻辑
en: Adapt the logic after moving the http2 logic to hertz-contrib
zh(optional): 适配将 http2 逻辑挪到 hertz-contrib 后的逻辑
=> feat: Adapt the logic after moving the http2 logic to hertz-contrib

pkg/protocol/response.go, pkg/protocol/response_test.go
feat
添加 `resp.SetBodyStreamNoReset` 方法
en: In the client streaming scenario gateway, the user wants to get the original bodystream for streaming processing, and put the processed data into a new resp bodystream and return it to the server. But the current SetBodyStream will turn off the original bodystream and the data cannot be processed, so add the SetBodyStreamNoReset method
zh(optional): 在 client 流式场景网关中，用户想要将原来的 bodystream 拿到进行流式处理，并将流式处理处理后的数据放到一个新的 resp bodystream 返回给 server。但是现在的 SetBodyStream 会将原来的 bodystream 关掉导致无法处理数据，所以添加 SetBodyStreamNoReset 方法
=> feat: add `resp.SetBodyStreamNoReset` method

pkg/app/client/retry/retry_test.go
pkg/app/client/retry/retry.go test coverage reached **_100%_**
为pkg/app/client/retry/retry.go添加测试
en: Add tests for pkg/app/client/retry/retry.go
zh(optional): 为pkg/app/client/retry/retry.go添加测试
#257
=> test: add tests for pkg/app/client/retry/retry.go

pkg/app/client/client_test.go, pkg/protocol/client/client.go
fix
在 HTTP2 场景下，`doRequestFollowRedirectsBuffer` 不能获取到 body
en: `doRequestFollowRedirectsBuffer` cannot get body in HTTP2 scenario. The affected interfaces include  `client.Get`，`client.GetTimeout`，`client.GetDeadLine`，`client.Post`
zh(optional): 在 HTTP2 场景下，`doRequestFollowRedirectsBuffer` 不能获取到 body，受影响的接口包括 `client.Get`，`client.GetTimeout`，`client.GetDeadLine`，`client.Post`
=> fix: `doRequestFollowRedirectsBuffer` cannot get body in HTTP2 scenario

pkg/app/server/hertz_test.go, pkg/protocol/http1/server.go
optimize
如果请求body体超出限制，则返回 413 状态码
en: server will return 413 error and with a body to describe the reason instead of 400 if request body size exceed the limit.
zh(optional): 如果请求正文大小超过限制，服务器将返回 413 错误并使用正文来描述原因而不是 400 解析错误。
=> optimize(http1): return 413 status code if request body is too large
