- pkg/app/client/client.go
- pkg/app/context.go
- pkg/app/middlewares/server/basic_auth/basic_auth.go
- pkg/common/timer/timer.go
> style(*): fix typos

- pkg/common/utils/ioutil.go
style
en：delete redundant type conversion
zh：删除多余的类型转换
> style：delete redundant type conversion

- .github/workflows/tests.yml
- README.md
- README_cn.md
docs
- en: add icon in README.md and README_cn.md
- zh: readme 文件中添加 icon
> docs: add icon in README.md and README_cn.md

- pkg/common/testdata/proto/test.pb.go
- pkg/route/engine.go
optimize
en: add remote address in the error log when server processing the error.
zh: 服务端错误日志中添加对端地址。
[#55]
> optimize: add remote address in the error log

- pkg/app/client/client.go
style
zh: 常量替换和去掉了重复的类型转换
en: use const var and removed duplicate type conversions
> style: use const var and removed duplicate type conversions

- pkg/protocol/cookie.go
refactor
en: use appendCookiePart function to simpify code
zh: 使用 appendCookiePart 函数简化代码
> refactor: use appendCookiePart to simpify code

- cmd/hz/internal/config/cmd.go
- cmd/hz/internal/meta/const.go
- cmd/hz/internal/protobuf/plugin.go
- cmd/hz/internal/util/data.go
- cmd/hz/internal/util/env.go
- cmd/hz/main.go
feat
en: hz feat windows
zh: hz 命名行工具支持windows
> feat: hz support windows

- pkg/route/tree.go
optimize
EN: remove useless judgement
ZH: 去掉无用逻辑
> optimize: remove useless judgement

- cmd/hz/internal/thrift/resolver.go
- pkg/app/context.go
- pkg/app/fs.go
- pkg/common/bytebufferpool/pool_test.go
- pkg/route/engine.go
refactor
EN：Fixed some typos and grammar errors and an extra pair of parentheses, also fixed an extra type cast
CN：修复了一些拼写错误和语法错误以及一对额外的括号，还修复了一个多余的类型转换
Not a fix for the issue
> style: fixed some typos and redundant code segments

- pkg/app/context.go
- pkg/app/middlewares/server/basic_auth/basic_auth.go
- pkg/app/server/option.go
- pkg/common/config/option.go
- pkg/protocol/client/client.go
- pkg/protocol/cookie.go
- pkg/protocol/header.go
- pkg/protocol/http1/client.go
- pkg/protocol/request.go
- pkg/protocol/response.go
- pkg/protocol/suite/server.go
style
en: fixed some translation grammar problems
zh: 修正了一些翻译语法问题
> style: Grammar correction

- pkg/app/server/hertz.go
feat
EN: add a way to customize the signal waiter logic
ZH：增加一个接口支持自定义信号捕捉逻辑，以便根据场景调节优雅退出需要应对的信号类型
> feat: custom signal to gracefull shutdown

- pkg/route/engine.go
feat
impl for #121 
closes #121
> feat: add option to remove hijackConnPool

- cmd/hz/internal/meta/const.go
chore
chore: update hz version v0.2.0
> chore: update hz version v0.2.0

- pkg/app/client/client.go
- pkg/app/client/client_test.go
- fix
- en: add missing port when use domain
- zh: 使用域名时添加默认端口
> fix: add missing port when use domain

- cmd/hz/internal/generator/router.go
fix
en: Fix the error when the last level of the route defined in idl is "/"
zh: 修复 idl 中定义的路由最后一级为"/"时的报错
> fix: generate router register error

- pkg/network/standard/connection.go
fix
- en: hijack conn throw timeout err when use standard network lib
https://github.com/cloudwego/hertz/issues/178
> fix: hijack conn throw timeout err when use standard network lib

- cmd/hz/internal/thrift/ast.go
fix
en: Fix the problem that the namespace suffix of thrift contains ".thrift".
zh: 修复thrift 的namespace尾缀包含".thrift"的问题
> fix: thrift namespace

- .codecov.yml
add example/* and cmd/* to codecov ignore
> add dir ignore

- cmd/hz/internal/thrift/ast.go
- cmd/hz/internal/thrift/name_style.go
- cmd/hz/internal/thrift/plugin.go
- cmd/hz/internal/util/data.go
fix
en: fix name style for thrift
zh: 修复thrift的命名方式，struct name 与 thriftgo 的 namestyle保持一致
> fix: name_style_thrift

- .codecov.yml
- .github/workflows/tests.yml
What type of PR is this?
chore: support codecov and file ignore
What this PR does / why we need it (en: English/zh: Chinese):
en: support codecov
zh: 支持 codecov
> chore: support codecov 

- cmd/hz/internal/generator/router.go
> Revert "fix: generate router register error"

- pkg/route/engine_test.go
test: add `route.GetTransporterName` unit test
> test: add GetTransporterName unit test

- cmd/hz/internal/generator/router.go
- cmd/hz/internal/protobuf/plugin.go
- cmd/hz/internal/protobuf/resolver.go
- cmd/hz/internal/thrift/plugin.go
- cmd/hz/internal/thrift/resolver.go
- cmd/hz/internal/util/data.go
- cmd/hz/internal/util/data_test.go
fix
en: fix the problem of the same package name in handler
zh: 修复handler中的引用相同包名的问题，并把获取unique变量名的方法单独提出来，
> fix: fix the problem of the same package name in handler

- cmd/hz/internal/generator/router.go
fix
en: modify the same middleware name
zh: 修改同名的路由组
> fix: modify the same middleware name

- .github/PULL_REQUEST_TEMPLATE.md
chore
chore: 修正 pull request 模板的语法问题
related pr #217  
none
> chore: fix grammer of pull request template

- go.mod
- go.sum
chore
- en: update sonic version
- ch: 更新 sonic 版本
> chore: update sonic version

- go.mod
- go.sum
chore
chore：更新 netpoll 的版本，v0.2.4 -> v0.2.6
en: update netpoll version, from v0.2.4 to v0.2.6
zh(optional): 更新 netpoll 的版本，v0.2.4 -> v0.2.6
> chore: update netpoll version

- pkg/app/client/client.go
refactor
重构 client 初始化 m 和 ms 的逻辑
en:  client init m and ms logic
zh(optional): 重构 client 初始化 m 和 ms 的逻辑
> refactor: client init m and ms logic

- pkg/app/server/option_test.go
test
en: enrich ut for `pkg/app/server/option.go`
none
> test: enrich ut for pkg/app/server/option.go

- .github/workflows/tests.yml
- pkg/common/json/sonic.go
- pkg/common/json/std.go
- pkg/network/netpoll/dial.go
- pkg/route/default.go
doc
en: modify header  licenses comment
zh(optional): 修改注释信息为行注释避免 buildtag 格式问题的导致 ci 报错
> chore: change license header style to avoid format error of buildtag from CI check

- README.md
- README_cn.md
docs
en: Add Slack to README.
zh: 在 README 中添加 Slack 。
> docs(README): add slack

- pkg/app/middlewares/client/sd/discovery.go
style
style: 替换 `sd.Discovery` 的返回类型为 `client.Middleware`
en: replace `func(next client.Endpoint) client.Endpoint` to `client.Middleware` 
zh(optional): 将 Discovery() 中返回的类型替换为 client.Middleware
> style: replace the return type of `sd.Discovery` with `client.Middleware`

- cmd/hz/internal/protobuf/ast.go
- cmd/hz/internal/protobuf/plugin.go
- cmd/hz/internal/protobuf/plugin_test.go
feat
修改 go package
en: modify go package
zh(optional):
> feat(hz): modify go package

- README.md
- README_cn.md
docs
在 README 中新增 logger 拓展
None.
> docs(README): add logger extension

- pkg/common/hlog/default_test.go
- pkg/common/hlog/hlog_test.go
- pkg/common/hlog/system_test.go
- pkg/protocol/header_test.go
test
en: add ut for pkg/common/hlog, coverage rate reached 81.4%
#293
> test: add ut for pkg/common/hlog

- cmd/hz/internal/app/app.go
- cmd/hz/internal/meta/const.go
- cmd/hz/internal/protobuf/plugin.go
- cmd/hz/internal/thrift/plugin.go
feat
添加只生成 model 代码的模式
en: only generate model mode
zh(optional): 添加只生成 model 代码的模式
> feat(hz): add model-only generating mode

- pkg/app/server/mocks_test.go
- pkg/common/errors/errors.go
- pkg/common/tracer/traceinfo/httpstats.go
- pkg/common/utils/netaddr.go
- pkg/protocol/http1/factory/client.go
- pkg/protocol/http1/factory/server.go
- pkg/route/routergroup.go
style
修改接口检查的方式。
en: For more details, see #346 .
zh: 更多信息，请详见 #346 。
#346
> style: modify interface check way.

- README.md
- README_cn.md
> docs(README): add contributors 

- README.md
- README_cn.md
docs
优化对 README 中 logger 的描述
None.
> docs(README): improve logger description

- pkg/route/engine.go
feat
适配将 http2 逻辑挪到 hertz-contrib 后的逻辑
en: Adapt the logic after moving the http2 logic to hertz-contrib
zh(optional): 适配将 http2 逻辑挪到 hertz-contrib 后的逻辑
> feat: Adapt the logic after moving the http2 logic to hertz-contrib

- README.md
- README_cn.md
docs
为 README 增加更加更多文章。
目前已更新与 Hertz 相关的文章均只有中文，因此目前在英文 README 的软链也是中文文章。可以后续发布 good first issue 让一些同学参与翻译。
Fixes #355
> docs(README): add more blogs

- pkg/common/utils/chunk_test.go
- pkg/common/utils/ioutil_test.go
- pkg/common/utils/netaddr_test.go
- pkg/common/utils/network_test.go
- pkg/common/utils/path_test.go
- pkg/common/utils/utils_test.go
test: pkg/common/utils test coverage increased from 66% to 81.8%
en:
zh(optional):
#257
> test: add more tests for pkg/common/utils

- pkg/app/client/discovery/discovery_test.go
pkg/app/client/discovery/discovery.go test coverage reached **_100%_**
为pkg/app/client/discovery/discovery.go添加测试
en: Add tests for pkg/app/client/discovery/discovery.go
zh(optional): 为pkg/app/client/discovery/discovery.go添加测试
#257
> test: add tests for pkg/app/client/discovery/discovery.go

- pkg/app/server/hertz.go
optimize
如果二进制文件由 nohup 运行，则忽略 sighup 信号
en: Golang listens to the sighup signal with a higher priority than nohup. If you start the binary directly through nohup, you will still receive the sighup signal (if any). Therefore, here adds an explicit judgment. If sighup has been ignored, it will no longer do monitoring processing.
zh(optional): Golang 监听 sighup 信号的优先级高于 nohup，如果通过 nohup 直接启动二进制，当前仍然会收到 sighup 信号（如果有的话）。因此我们增加一个显式判断，如果 sighup 已经被忽略，就不再做监听处理了。
> optimize: ignore sighup signal if binary is run by nohup

- pkg/app/context_test.go
pkg/app/context test coverage increased from 68.6% to 73.8%
为pkg/app/context添加更多测试
en: Add tests for TraceInfo Get and Set operations for pkg/app/context
zh(optional): 为pkg/app/context添加TraceInfo读写操作的测试
#257
> test: add more tests for pkg/app/context

- .github/labels.json
- .github/workflows/invalid_question.yml
- .github/workflows/labeler.yml
ci
添加 labeler 来规范使用 issue 模版。
There are often users who do not follow the issue template when submitting issues. Adding a labeler can effectively avoid this problem.
When it is judged as `invalid issue`, there will be a buffer period of 3 days. If there is no change, this issue will be closed directly.
When the issue is edited, it will be checked again, and if there is no problem, the label will be removed.
None.
> ci: add a labeler to limit the specification of the issue template

- pkg/app/server/registry/registry_test.go
pkg/app/server/registry test coverage reached **_100%_**
为 pkg/app/server/registry添加测试
en: Add tests for  pkg/app/server/registry
zh(optional): 为 pkg/app/server/registry添加测试
#257
> test: add tests for pkg/app/server/registry

- pkg/app/server/hertz_test.go
- pkg/app/server/option.go
- pkg/common/config/option.go
- pkg/network/netpoll/transport.go
- pkg/network/standard/transport.go
feat
添加 transporter 配置
en: Add `OnAccept` and `OnConnect` for transporter
zh(optional): 为 transporter 添加 OnAccept 和 OnConnect 方法
> feat: add transporter config
